default_language_version:
  python: python3.6
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.8.2
  hooks:
  - id: reorder-python-imports
    args: [--py36-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
  - id: pyupgrade
    args: [--py36-plus]

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  #- id: check-yaml
  - id: debug-statements
- repo: https://github.com/pycqa/flake8
  rev: '5.0.4'
  hooks:
  - id: flake8
    exclude: tests
    additional_dependencies:
    - flake8-quotes>=3.2
    - flake8-docstrings>=1.5
